#!/usr/bin/env php
<?php

$host = getenv('POSTGRES_HOST');
$dbUser = getenv('POSTGRES_USER');
$dbPassword = getenv('POSTGRES_PASSWORD');

if ($argc > 1) {
    try {
        $pdo = new PDO("pgsql:host={$host};dbname=postgres", $dbUser, $dbPassword);
        foreach (array_slice($argv, 1) as $database) {
            $dbCheck = $pdo
                ->query("SELECT EXISTS(SELECT * FROM pg_catalog.pg_database WHERE datname = '{$database}')")
                ->fetch();
           if (!$dbCheck['exists']) {
               $pdo->exec("CREATE DATABASE {$database} WITH TEMPLATE 'template0' ENCODING 'utf8'");
           }
        }
    } catch (Throwable $e) {
        throw new Exception($e->getMessage());
    }
} else {
    echo "Supply at least one database name as an argument\r\n";
}
